---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Anonymous Ded Morozes backyard infrastructure

Parameters:
  sentryDsn:
    Type: String
    Description: Sentry DSN

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/main.js
      Runtime: nodejs20.x
      PackageType: Zip
      Handler: main.handler
      Timeout: 20
      FunctionName: gnomik-api-function

      Environment:
        Variables:
          NODE_ENV: production
          SENTRY_DSN: !Ref sentryDsn

      Events:
        RootGet:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: MyApi
        ErrorGet:
          Type: Api
          Properties:
            Path: /error
            Method: get
            RestApiId:
              Ref: MyApi

  MyApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref MyApi
      DomainName: api.gnomik.me
      Stage: prod
