name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: uglyunicorn-eh/prostir-github-tools/.github/workflows/node-aws-serverless-deploy.yml@main
    secrets: inherit
